add_as_data_stewards: []
allow_read_paths:
- /.well-known/*
- /service-logo.png
allow_write_paths: []
api_ext_path: /api/auth
api_root_path: ''
auth_algs:
- ES256
auth_check_claims:
  email: null
  exp: null
  iat: null
  id: null
  name: null
auth_ext_algs:
- RS256
- ES256
auth_ext_keys: null
auth_key: null
auth_map_claims: {}
auth_paths:
- /api/
auth_topic: auth
auto_reload: true
basic_auth_credentials: null
basic_auth_realm: GHGA Data Portal
claims_collection: claims
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
cors_exposed_headers: null
csrf_token_bytes: 24
dataset_change_topic: metadata_datasets
dataset_deletion_type: dataset_deleted
dataset_upsertion_type: dataset_created
db_name: dev-db
db_version_collection: authDbVersions
docs_url: /docs
enable_opentelemetry: false
generate_correlation_id: true
host: 0.0.0.0
iva_send_code_type: iva_send_code
iva_state_changed_topic: ivas
iva_state_changed_type: iva_state_changed
ivas_collection: ivas
kafka_compression_type: null
kafka_dlq_topic: dlq
kafka_enable_dlq: false
kafka_max_message_size: 1048576
kafka_max_retries: 0
kafka_retry_backoff: 0
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: DEBUG
log_traceback: true
max_iva_verification_attempts: 10
migration_max_wait_sec: null
migration_wait_sec: 10
mongo_dsn: '**********'
mongo_timeout: null
oidc_authority_url: https://login.aai.lifescience-ri.eu/oidc/
oidc_client_id: ghga-data-portal
oidc_issuer: https://login.aai.lifescience-ri.eu/oidc/
oidc_userinfo_endpoint: https://login.aai.lifescience-ri.eu/oidc/userinfo
openapi_url: /openapi.json
organization_url: https://ghga.de/
otel_trace_sampling_rate: 1.0
port: 8080
provide_apis:
- users
run_consumer: false
second_factor_recreated_type: second_factor_recreated
service_instance_id: '1'
service_name: auth_service
session_id_bytes: 24
session_max_lifetime_seconds: 43200
session_timeout_seconds: 3600
totp_algorithm: sha1
totp_attempts_per_code: 3
totp_digits: 6
totp_encryption_key: null
totp_image: null
totp_interval: 30
totp_issuer: GHGA
totp_max_failed_attempts: 10
totp_secret_size: 32
totp_tolerance: 1
user_tokens_collection: user_tokens
user_topic: users
users_collection: users
workers: 1
