# Only required if the service is using an SQL-based Database,
# can be deleted otherwise.

name: Check if DB migration scripts are up to date

on: push

jobs:
  # Please adapt to package
  # Please remove this dummy job and
  # uncomment the sections that follows to enable this workflow.
  dummy_job:
    runs-on: ubuntu-latest
    steps:
      - id: dummy_job
        run: echo "this is a dummy job"

  # check_db_migration_scripts:
  #   runs-on: ubuntu-latest
  #   name: Check if DB migration scripts are up to date
  #   env:
  #     DB_URL: postgresql://postgres:postgres@localhost/postgres
  #   services:
  #     postgres:
  #       image: postgres:latest
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_DB: postgres
  #         POSTGRES_PASSWORD: postgres
  #       ports:
  #         - 5432:5432
  #       # set health checks to wait until postgres has started
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - uses: actions/checkout@v2.4.2

  #     - id: common
  #       uses: ghga-de/gh-action-common@v1.0.2

  #     - name: try to update db
  #       run: |
  #         export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"
  #         cd ./db_migration
  #         alembic upgrade head

  #     - name: check if DB migration scripts are up to date
  #       run: |
  #         export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"
  #         cd ./db_migration
  #         alembic-autogen-check
