name: Dev CD

on:
  push:
    branches:
      - "main"
      # you may add other branches to
      # activate deployment for them, too.

jobs:
  get_commit_version:
    runs-on: ubuntu-latest
    outputs:
      # export to be used in other jobs
      version: ${{ steps.get_commit_version.outputs.version }}
      branch: ${{ steps.get_commit_version.outputs.branch }}
    steps:
      - uses: actions/checkout@v2.4.2
        name: Check out code
        with:
          # fetch the entire history
          fetch-depth: 0

      - id: get_commit_version
        name: get commit version
        run: |
          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if git describe --tags
          then
            VERSION="$(git describe --tags)-${BRANCH}"
          else
            # fallback if no tag set yet:
            COMMIT_HASH="$(git rev-parse --short HEAD)"
            COMMIT_NUMBER="$(git rev-list --count HEAD)"
            VERSION="0.0.0-${COMMIT_NUMBER}-${COMMIT_HASH}-${BRANCH}"
          fi
          # set as output:
          echo "commit version: ${BRANCH}"
          echo "commit version: ${VERSION}"
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=branch::${BRANCH}"

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: get_commit_version
    steps:
      - uses: actions/checkout@v2.4.2
        name: Check out code

      - uses: docker/setup-qemu-action@v2.0.0
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2.0.0
        name: Set up Docker Buildx

      - uses: docker/login-action@v2.0.0
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3.0.0
        name: Build and push
        id: docker_build
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: "ghga/${{ github.event.repository.name }}:${{ needs.get_commit_version.outputs.version }},ghga/${{ github.event.repository.name }}:${{ needs.get_commit_version.outputs.branch }}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  ## Please uncomment and adapt the DEPLOYMENT_CONFIG_REPO to trigger automatic
  ## updates of helm charts:
  # update_deployment_repo:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - get_commit_version
  #     - push_to_docker_hub
  #   env:
  #     DEPLOYMENT_CONFIG_REPO: ghga-de/helm
  #   steps:
  #     - name: trigger update in deployment repo
  #       run: |
  #         # access token needs to be of format: <username>:<personal_access_token>
  #         curl -X POST \
  #           "https://api.github.com/repos/${DEPLOYMENT_CONFIG_REPO}/dispatches" \
  #           -H 'Accept: application/vnd.github.everest-preview+json' \
  #           -u '${{ secrets.DEPLOYMENT_UPDATE_TOKEN }}' \
  #           --data '{
  #             "event_type": "new_app_version",
  #             "client_payload": {
  #               "chart_name": "${{ github.event.repository.name }}",
  #               "context": "${{ needs.get_commit_version.outputs.branch }}",
  #               "new_app_version": "${{ needs.get_commit_version.outputs.version }}"
  #             }
  #           }'
